name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}  # Corrected input for server
        username: ${{ secrets.FTP_USERNAME }}  # Corrected input for username
        password: ${{ secrets.FTP_PASSWORD }}  # Corrected input for password
        local-dir: ./  # Local directory to deploy from
        server-dir: /  # Correct server directory path (ending with /)